version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=url.emith.dev
      - LETSENCRYPT_HOST=url.emith.dev
      - LETSENCRYPT_EMAIL=webmaster@emith.dev
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
